// Mocks generated by Mockito 5.3.2 from annotations
// in s_c/test/app_test/domain/repositories/app_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:s_c/app/data/datasources/app_local_data_source.dart' as _i2;
import 'package:s_c/core/usecases/usecase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalDataSource extends _i1.Mock
    implements _i2.AppLocalDataSource {
  MockAppLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> cachedAccount({
    required String? username,
    required String? password,
    required String? uid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cachedAccount,
          [],
          {
            #username: username,
            #password: password,
            #uid: uid,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> clearCachedAccount({required _i4.NoParams? noParams}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCachedAccount,
          [],
          {#noParams: noParams},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
