// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXE4tub6v2XPM7ZAQr28UOCa1e9FMkrms',
    appId: '1:247422761988:web:5acf11f8a2059457f6c951',
    messagingSenderId: '247422761988',
    projectId: 'scdev-9d023',
    authDomain: 'scdev-9d023.firebaseapp.com',
    databaseURL: 'https://scdev-9d023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scdev-9d023.appspot.com',
    measurementId: 'G-2ZHXKCQLWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0HGtT776sBdGnrfmdfp60i4WuGPKNJVM',
    appId: '1:247422761988:android:0e147cb42a5626e7f6c951',
    messagingSenderId: '247422761988',
    projectId: 'scdev-9d023',
    databaseURL: 'https://scdev-9d023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scdev-9d023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBiDFG2Zu3kmYEJPZDBGWWJXjFgRe2MNk',
    appId: '1:247422761988:ios:c023ed5fd077578bf6c951',
    messagingSenderId: '247422761988',
    projectId: 'scdev-9d023',
    databaseURL: 'https://scdev-9d023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scdev-9d023.appspot.com',
    iosClientId: '247422761988-8uhi5j5mc7j4d1bc4lba7mmdh6k44sps.apps.googleusercontent.com',
    iosBundleId: 'com.vuongdan.sc.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBiDFG2Zu3kmYEJPZDBGWWJXjFgRe2MNk',
    appId: '1:247422761988:ios:60bc64d946c7db4ff6c951',
    messagingSenderId: '247422761988',
    projectId: 'scdev-9d023',
    databaseURL: 'https://scdev-9d023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scdev-9d023.appspot.com',
    iosClientId: '247422761988-asu9hsk40p4gstrv98dragndkdol9pd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sc',
  );
}
