// Mocks generated by Mockito 5.3.2 from annotations
// in s_c/test/features/login_test/presentation/cubit/login_test_cubit.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:s_c/app/domain/entities/sc_user.dart' as _i7;
import 'package:s_c/core/error/failures.dart' as _i6;
import 'package:s_c/features/login/domain/repositories/login_repository.dart'
    as _i2;
import 'package:s_c/features/login/domain/usecases/login_with_username_and_pw.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginRepository_0 extends _i1.SmartFake
    implements _i2.LoginRepository {
  _FakeLoginRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginWithUsernameAndPw].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithUsernameAndPw extends _i1.Mock
    implements _i3.LoginWithUsernameAndPw {
  MockLoginWithUsernameAndPw() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoginRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLoginRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LoginRepository);
  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.SCUser>?> call(_i7.SCUser? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.SCUser>?>.value(),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i7.SCUser>?>);
}
