// Mocks generated by Mockito 5.3.2 from annotations
// in s_c/test/features/user_profile_test/domain/repositories/user_profile_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:s_c/core/network/network_info.dart' as _i5;
import 'package:s_c/features/user_profile/data/datasources/user_profile_remote_data_source.dart'
    as _i3;
import 'package:s_c/features/user_profile/data/models/user_profile_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfileModel_0 extends _i1.SmartFake
    implements _i2.UserProfileModel {
  _FakeUserProfileModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRemoteDataSource extends _i1.Mock
    implements _i3.UserProfileRemoteDataSource {
  MockUserProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserProfileModel> getUserProfile({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i4.Future<_i2.UserProfileModel>.value(_FakeUserProfileModel_0(
          this,
          Invocation.method(
            #getUserProfile,
            [],
            {#userId: userId},
          ),
        )),
      ) as _i4.Future<_i2.UserProfileModel>);
  @override
  _i4.Future<_i2.UserProfileModel> setUserProfile({
    required String? userId,
    required _i2.UserProfileModel? userProfile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserProfile,
          [],
          {
            #userId: userId,
            #userProfile: userProfile,
          },
        ),
        returnValue:
            _i4.Future<_i2.UserProfileModel>.value(_FakeUserProfileModel_0(
          this,
          Invocation.method(
            #setUserProfile,
            [],
            {
              #userId: userId,
              #userProfile: userProfile,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserProfileModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [UserProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class UserProfileRemoteDataSourceForTest extends _i1.Mock
    implements _i3.UserProfileRemoteDataSource {
  @override
  _i4.Future<_i2.UserProfileModel> getUserProfile({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i4.Future<_i2.UserProfileModel>.value(_FakeUserProfileModel_0(
          this,
          Invocation.method(
            #getUserProfile,
            [],
            {#userId: userId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserProfileModel>.value(_FakeUserProfileModel_0(
          this,
          Invocation.method(
            #getUserProfile,
            [],
            {#userId: userId},
          ),
        )),
      ) as _i4.Future<_i2.UserProfileModel>);
  @override
  _i4.Future<_i2.UserProfileModel> setUserProfile({
    required String? userId,
    required _i2.UserProfileModel? userProfile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserProfile,
          [],
          {
            #userId: userId,
            #userProfile: userProfile,
          },
        ),
        returnValue:
            _i4.Future<_i2.UserProfileModel>.value(_FakeUserProfileModel_0(
          this,
          Invocation.method(
            #setUserProfile,
            [],
            {
              #userId: userId,
              #userProfile: userProfile,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserProfileModel>.value(_FakeUserProfileModel_0(
          this,
          Invocation.method(
            #setUserProfile,
            [],
            {
              #userId: userId,
              #userProfile: userProfile,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserProfileModel>);
}
